"""change logging column

Revision ID: 3ccbbce0d6e9
Revises: d758b9f43987
Create Date: 2025-11-06 10:29:54.139558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ccbbce0d6e9'
down_revision: Union[str, Sequence[str], None] = 'd758b9f43987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_images_item_id'), table_name='item_images')
    op.add_column('logging', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('logging', 'tablename',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('logging', 'operation',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('logging', 'new_val',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('logging', 'old_val',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('logging', 'tstamp')
    op.drop_constraint(op.f('memberships_approver_fkey'), 'memberships', type_='foreignkey')
    op.drop_column('memberships', 'approver')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('approver', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('memberships_approver_fkey'), 'memberships', 'users', ['approver'], ['id'])
    op.add_column('logging', sa.Column('tstamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('logging', 'old_val',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('logging', 'new_val',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('logging', 'operation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('logging', 'tablename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('logging', 'created_at')
    op.create_index(op.f('ix_item_images_item_id'), 'item_images', ['item_id'], unique=False)
    # ### end Alembic commands ###
