"""added logging table

Revision ID: 65a1ab6ee3a3
Revises: fb9bc83de921
Create Date: 2025-10-07 22:56:29.510770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '65a1ab6ee3a3'
down_revision: Union[str, Sequence[str], None] = 'fb9bc83de921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    borrowstatus = postgresql.ENUM(
        'PENDING_APPROVAL', 'APPROVED', 'PENDING_CONDITION_CHECK', 'COMPLETED', 'REJECTED',
        name='borrowstatus'
    )
    borrowstatus.create(op.get_bind(), checkfirst=True)

    itemstatus = postgresql.ENUM(
        'AVAILABLE', 'OUT_OF_SERVICE', 'PENDING_BORROWAL', 'BORROWED', 'PENDING_RETURN',
        name='itemstatus'
    )
    itemstatus.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tablename', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('who', sa.Integer(), nullable=False),
    sa.Column('new_val', sa.JSON(), nullable=True),
    sa.Column('old_val', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['who'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('item_borrowing_transactions', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING_APPROVAL', 'APPROVED', 'PENDING_CONDITION_CHECK', 'COMPLETED', 'REJECTED', name='borrowstatus'),
               postgresql_using="status::borrowstatus",
               existing_nullable=False)
    
    op.execute("ALTER TABLE items ALTER COLUMN status DROP DEFAULT")

    op.alter_column('items', 'status',
               existing_type=sa.VARCHAR(),
               type_=itemstatus,
               existing_nullable=False,
                postgresql_using="status::itemstatus",
               existing_server_default=sa.text("'available'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'status',
               existing_type=sa.Enum('AVAILABLE', 'OUT_OF_SERVICE', 'PENDING_BORROWAL', 'BORROWED', 'PENDING_RETURN', name='itemstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'available'::character varying"))
    op.alter_column('item_borrowing_transactions', 'status',
               existing_type=sa.Enum('PENDING_APPROVAL', 'APPROVED', 'PENDING_CONDITION_CHECK', 'COMPLETED', 'REJECTED', name='borrowstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('logging')
    # ### end Alembic commands ###
