"""Changed type of membership and global roles to int

Revision ID: 933a9d5f6f70
Revises: 141ba3c03143
Create Date: 2025-09-30 22:25:06.890033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '933a9d5f6f70'
down_revision: Union[str, Sequence[str], None] = '141ba3c03143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'global_role',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="global_role::integer")
    
    op.alter_column('memberships', 'role',
                existing_type=sa.VARCHAR(),
                type_=sa.Integer(),
                existing_nullable=False,
                postgresql_using="role::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'global_role',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="global_role::varchar")
    
    op.alter_column('memberships', 'role',
                existing_type=sa.Integer(),
                type_=sa.VARCHAR(),
                existing_nullable=False,
                postgresql_using="role::varchar")
    # ### end Alembic commands ###
