"""added status column for items

Revision ID: d3b17db42289
Revises: 5d97fd55745c
Create Date: 2025-10-02 10:42:03.032388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b17db42289'
down_revision: Union[str, Sequence[str], None] = '5d97fd55745c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('status', sa.String(), server_default='available', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'status')
    # ### end Alembic commands ###
