"""add email sent boolean in request

Revision ID: ddc127492145
Revises: eb0e56e898ba
Create Date: 2025-10-25 01:27:11.093857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc127492145'
down_revision: Union[str, Sequence[str], None] = 'eb0e56e898ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_borrowing_requests', sa.Column('is_warning_email_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_borrowing_requests', 'is_warning_email_sent')
    # ### end Alembic commands ###
