"""Added Borrowing tables

Revision ID: fb9bc83de921
Revises: 8b1a5691fb7b
Create Date: 2025-10-07 19:54:24.789830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9bc83de921'
down_revision: Union[str, Sequence[str], None] = '8b1a5691fb7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy import inspect

def upgrade() -> None:
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()

    if 'item_borrowing_requests' not in existing_tables:
        op.create_table('item_borrowing_requests',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('item_id', sa.Integer(), nullable=False),
            sa.Column('borrower_id', sa.Integer(), nullable=False),
            sa.Column('return_date', sa.TIMESTAMP(timezone=True),
                      server_default=sa.text("now() + interval '7 days'"), nullable=False),
            sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                      server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )

    if 'item_borrowing_transactions' not in existing_tables:
        op.create_table('item_borrowing_transactions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('item_borrowing_request_id', sa.Integer(), nullable=False),
            sa.Column('processed_at', sa.TIMESTAMP(timezone=True),
                      server_default=sa.text('now()'), nullable=False),
            sa.Column('operator_id', sa.Integer(), nullable=True),
            sa.Column('status', sa.String(), nullable=False),
            sa.Column('remarks', sa.String(), nullable=True),
            sa.ForeignKeyConstraint(['item_borrowing_request_id'], ['item_borrowing_requests.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
            sa.PrimaryKeyConstraint('id')
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_borrowing_transactions')
    op.drop_table('item_borrowing_requests')
    # ### end Alembic commands ###
